// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xyyfpbsklqfqdhjkvdvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5eWZwYnNrbHFmcWRoamt2ZHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODc4MDUsImV4cCI6MjA2NjI2MzgwNX0.VcCZWqlOf7UKbR2rReZ5PrPAMS1aHhzTiKuLUfzshOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);